services:
    nginx:
        container_name: nginx
        #image: nginx
        build: /requiriments/wordpress
            #context: /requiriments/nginx
            #dockerimage: Dockerfile
        ports:
            -"443:443"
            -"80:80"
        depends-on:
            -wordpress
        networks:
            -inception
        volumes:
            -wp_data: /var/www/html
    wordpress:
        #image: wordpress
        build: /requiriments/wordpress
            #context: /requiriments/wordpress
            #dockerimage: Dockerfile
        ports:
            -"9000:9000"
        depends-on:
            mariadb
        networks:
            -inception
        volumes:
            -wp_data: /var/www/html
    mariadb:
        #image: mariadb
        build: /requiriments/mariadb
        #    context: 
        #   dockerimage: Dockerfile
        ports:
            -"3306:3306"
        networks:
            -inception
        volumes:
            -mdb_data: /var/lib/mysql
networks:
    inception:
        -nginx
        -wordpress
        -mariadb
volumes:
    wp_data: volumes/wordpress
    mdb_data: volumes/mariadb
