services:
    nginx:
        container_name: nginx
        build: ./requiriments/nginx
        ports:
            - "443:443"
        depends_on:
            - wordpress
        networks:
            - nginx-wp
        volumes:
            - "wp_data:/var/www/html"
        restart: on-failure
    wordpress:
        container_name: wordpress
        build: ./requiriments/wordpress
        ports:
            - "9000:9000"
        depends_on:
            - mariadb
        networks:
            - nginx-wp
            - wp-mdb
        volumes:
            - "wp_data:/var/www/html"
        restart: on-failure
    mariadb:
        container_name: mariadb
        build: ./requiriments/mariadb
        ports:
            - "3306:3306"
        networks:
            - wp-mdb
        volumes:
            - "mdb_data:/var/lib/mysql"
        restart: on-failure
networks:
    nginx-wp:
        driver: bridge
    wp-mdb:
        driver: bridge
volumes:
    wp_data:
        driver: local
        driver_opts:
            type: none
            device: "/Users/pfuentes/Desktop/inception_prueba/srcs/volumes/wordpress"
            o: bind
    mdb_data:
        driver: local
        driver_opts:
            type: none
            device: "/Users/pfuentes/Desktop/inception_prueba/srcs/volumes/mariadb"
            o: bind
