# docker-compose.yml

version: "3.8"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    volumes:
        - "wordpress_volume:/wordpress"
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - wordpress-nginx
    restart: on-failure
    depends_on:
      - wordpress
    
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    volumes:
        - "wordpress_volume:/wordpress"
    env_file:
      - .env
    networks:
      - wordpress-mariadb
      - wordpress-nginx
    depends_on:
      - mariadb
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    volumes:
        - database:/var/lib/mysql
    env_file:
      - .env
    networks:
      - wordpress-mariadb
    restart: on-failure

networks:
  wordpress-nginx:
  wordpress-mariadb:

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/pfuentes/data/db
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/pfuentes/data/wordpress
      o: bind
