version: 2

services:
    nginx:
        container_name: nginx
        #image: nginx
        build:
            context: /requiriments/nginx
            dockerimage: Dockerfile
        ports:
            -"443:443"
            -"80:80"
        depends-on:
            -wordpress
        networks:
            -inception
    wordpress:
        #image: wordpress
        build:
            context: /requiriments/wordpress
            dockerimage: Dockerfile
        ports:
            -"9000:9000"
        depends-on:
            mariadb
        networks:
            -inception
        volumes:
            -wp_data: /var/www/html
    mariadb:
        image: mariadb
        #build: ./mariadb
        ports:
            -"3306:3306"
         networks:
             -inception
         volumes:
             -mdb_data: /var/lib/mysql
networks:
    inception:
        -nginx
        -wordpress
        -mariadb
volumes:
    wp_data: 
    mdb_data:
