FROM debian:bullseye

#EXPOSE 9000

#instalar php
RUN	apt-get update && apt-get upgrade
RUN apt install php php7.3-fpm mariadb-client php-mysql php-zip php-gd -y curl -y wget tar
#RUN	mkdir -p /srv/www
#RUN chown www-data: /srv/www

#instalar wordpress
#RUN wget http://wordpress.org/latest.tar.gz
#RUN tar xfz latest.tar.gz
#RUN mv wordpress/* .
#RUN rm -rf latest.tar.gz
#RUN rm -rf wordpress

COPY tools/script.sh /usr/local/bin/script.sh
RUN chmod +x /usr/local/bin/script.sh

CMD ["/usr/local/bin/script.sh"] 
