FROM 8.0-fpm-alpine
RUN	apt-get update && apt-get upgrade
RUN fetch https://ams.edge.kernel.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz && fetch https://ams.edge.kernel.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
RUN wget -q https://packages.sury.org/php/apt.gpg -O- | sudo apt-key add -
RUN sudo echo "deb https://packages.sury.org/php/ buster main" | tee /etc/apt/sources.list.d/php.list
RUN apt install php php-fpm php-mysql php-zip php-gd -y //instalar php
RUN	mkdir -p /srv/www
RUN chown www-data: /srv/www

#instalar wordpress
RUN apt install tar #instalar tar para descomprimir fichero
RUN curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx - C /sv/www #descargar de enlace
RUN tar -xzvf latest.tar.gz #descomprimir fichero .tar
RUN chown -R www-data:www-data /var/www/html
COPY /tools/wp-config.php wp-config.php 

CMD ["script.sh"] 
