FROM debian:buster
#instalar php
RUN	apt-get update && apt-get upgrade
RUN apt install php php-fpm php-mysql php-zip php-gd -y curl -y
RUN	mkdir -p /srv/www
RUN chown www-data: /srv/www

#instalar wordpress
RUN apt install tar 
RUN curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx - C /sv/www
RUN tar -xzvf latest.tar.gz
RUN chown -R www-data:www-data /var/www/html
COPY /tools/wp-config.php wp-config.php 

CMD ["script.sh"] 
